# Generated by Django 5.1.7 on 2025-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_itemcomanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='status',
            field=models.CharField(default='activ', max_length=10),
        ),
    ]
