# Generated by Django 5.1.7 on 2025-03-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_comanda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='status',
        ),
    ]
