# Generated by Django 5.1.7 on 2025-03-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_remove_comanda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('in_cos', 'În Coș'), ('plasata', 'Plasată'), ('procesata', 'Procesată'), ('livrata', 'Livrată'), ('anulata', 'Anulată')], default='in_cos', max_length=20),
        ),
    ]
