# Generated by Django 5.1.7 on 2025-03-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0006_comanda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='metoda_livrare',
            field=models.CharField(choices=[('curier', 'Curier rapid'), ('easybox', 'Easybox')], default='curier', max_length=20),
        ),
        migrations.AddField(
            model_name='comanda',
            name='metoda_plata',
            field=models.CharField(choices=[('card', 'Card bancar'), ('ramburs', 'Plată la livrare')], default='card', max_length=20),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('in_cos', 'În Coș'), ('plasata', 'Plasată'), ('procesata', 'Procesată'), ('livrata', 'Livrată'), ('anulata', 'Anulată')], default='in_asteptare', max_length=20),
        ),
    ]
